version: "3.9"

services:
  app:
    container_name: 'news_app'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - /app/node_modules
      - /app/build
      - .:/app
    environment:
      NODE_ENV: 'dev'
      REACT_APP_ENV: 'dev'
